// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXeGjObjeGrLJvG-q6l_HSfEKUx6BWmA',
    appId: '1:798479733635:web:98937e8652d1bda56b1cb6',
    messagingSenderId: '798479733635',
    projectId: 'conveydyn-project',
    authDomain: 'conveydyn-project.firebaseapp.com',
    storageBucket: 'conveydyn-project.firebasestorage.app',
    measurementId: 'G-V8L6YH792Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlrMOeofLwa2YPZpxpOFoRYjcmU45s10',
    appId: '1:798479733635:android:a5712dc99d772ad66b1cb6',
    messagingSenderId: '798479733635',
    projectId: 'conveydyn-project',
    storageBucket: 'conveydyn-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqICYM7y_KFhjANBVj1cmJjNMLH4Kg2W4',
    appId: '1:798479733635:ios:08daa72495e2a4c06b1cb6',
    messagingSenderId: '798479733635',
    projectId: 'conveydyn-project',
    storageBucket: 'conveydyn-project.firebasestorage.app',
    iosBundleId: 'com.example.testProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqICYM7y_KFhjANBVj1cmJjNMLH4Kg2W4',
    appId: '1:798479733635:ios:08daa72495e2a4c06b1cb6',
    messagingSenderId: '798479733635',
    projectId: 'conveydyn-project',
    storageBucket: 'conveydyn-project.firebasestorage.app',
    iosBundleId: 'com.example.testProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDXeGjObjeGrLJvG-q6l_HSfEKUx6BWmA',
    appId: '1:798479733635:web:abbfb97ac92374c86b1cb6',
    messagingSenderId: '798479733635',
    projectId: 'conveydyn-project',
    authDomain: 'conveydyn-project.firebaseapp.com',
    storageBucket: 'conveydyn-project.firebasestorage.app',
    measurementId: 'G-NW88N1KXDV',
  );
}
